src/web_site/app04_movies/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.MoviesView.as_view(), name='movie-list'),
    path('filter/', views.FilterMoviesView.as_view(), name='filter-link'),
    path('search/', views.Search.as_view(), name='search-link'),
    path('add-rating/', views.AddStarRating.as_view(), name='add-rating'),
    path('<slug:slug>/', views.MovieDetailView.as_view(), name='movie-detail'),
    path('review/<int:pk>/', views.AddReview.as_view(), name='add-review'),
    path('actor/<str:slug>/', views.ActorView.as_view(), name='actor-detail'),

]

src/web_site/web_site/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/',                  admin.site.urls),
    path('accounts/',               include('allauth.urls')),
    path('ckeditor/',               include('ckeditor_uploader.urls')),
    path('pages/',                  include('django.contrib.flatpages.urls')),
    path('contact/',                include('app05_contact.urls')),
    path('',                        include('app04_movies.urls')),
    path('__debug__/',              include('debug_toolbar.urls')),
]

src/web_site/app04_movies/models.py
from datetime import date
from django.db import models
from django.urls import reverse


class Category(models.Model):
    """ Категории """
    name = models.CharField('Категория', max_length=150)
    description = models.TextField('Описание')
    url = models.SlugField(max_length=160, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'


class Actor(models.Model):
    """ Актёры и режиссёры """
    name = models.CharField('Имя', max_length=100)
    age = models.PositiveSmallIntegerField('Возраст', default=0)
    description = models.TextField('Описание')
    image = models.ImageField('Изображение', upload_to='actors/')

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('actor-detail', kwargs={"slug": self.name})

    class Meta:
        verbose_name = 'Актёры и режиссёры'
        verbose_name_plural = 'Актёры и режиссёры'
        default_related_name = 'genres'


class Genre(models.Model):
    """ Жанры """
    name = models.CharField('Имя', max_length=100)
    description = models.TextField('Описание')
    url = models.SlugField(max_length=160, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Жанр'
        verbose_name_plural = 'Жанры'
        default_related_name = 'actors'


class Movie(models.Model):
    """ Фильмы """
    title = models.CharField("Название", max_length=100)
    # tagline = models.CharField("Слоган", max_length=100, default='')
    description = models.TextField("Описание")
    poster = models.ImageField("Постер", upload_to="movies/")
    year = models.PositiveSmallIntegerField("Дата выхода", default=2019)
    country = models.CharField("Страна", max_length=30)
    seasons = models.SmallIntegerField("Сезоны", default=0)
    series = models.SmallIntegerField("Серии", default=0)
    trailer = models.CharField("Трейлер", max_length=150, blank=True, null=True)

    @property
    def trailer_url(self):
        return self.trailer.replace('watch?v=', 'embed/')

    directors = models.ManyToManyField(
        Actor,
        verbose_name="режиссер",
        related_name="film_director")
    actors = models.ManyToManyField(
        Actor,
        verbose_name="актеры",
        related_name="film_actor")
    genres = models.ManyToManyField(
        Genre,
        verbose_name="жанры")

    world_premiere = models.DateField("Примьера в мире", default=date.today)
    category = models.ForeignKey(
        Category,
        verbose_name="Категория",
        on_delete=models.SET_NULL,
        null=True
    )

    url = models.SlugField(max_length=130, unique=True,)
    draft = models.BooleanField("Черновик", default=False)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("movie-detail", kwargs={"slug": self.url})

    def get_review(self):
        return self.reviews_set.filter(parent__isnull=True)

    class Meta:
        verbose_name = "Фильм"
        verbose_name_plural = "Фильмы"
        index_together = [
            ["url", ],
        ]


class MovieShots(models.Model):
    """Кадры из фильма"""
    title = models.CharField("Заголовок", max_length=100)
    # description = models.TextField(
    #     "Описание",
    #     blank=True,
    #     null=True
    # )
    image = models.ImageField("Изображение", upload_to="movie_shots/")

    movie = models.ForeignKey(
        Movie,
        verbose_name="Фильм",
        on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Кадр из фильма"
        verbose_name_plural = "Кадры из фильма"


class RatingStar(models.Model):
    """ Звезда рейтинга """
    value = models.SmallIntegerField("Значение", default=0)

    def __str__(self):
        return f'{self.value}'

    class Meta:
        verbose_name = "Звезда рейтинга"
        verbose_name_plural = "Звезды рейтинга"
        ordering = ["-value"]  # Сортировка по полю, отображение звёзд от > к <


class Rating(models.Model):
    """Рейтинг"""
    ip = models.CharField("IP адрес", max_length=15)

    star = models.ForeignKey(
        RatingStar,
        on_delete=models.CASCADE,
        verbose_name="звезда")
    movie = models.ForeignKey(
        Movie,
        on_delete=models.CASCADE,
        verbose_name="фильм",
        related_name="ratings")

    def __str__(self):
        return f"{self.star} - {self.movie}"

    class Meta:
        verbose_name = "Рейтинг"
        verbose_name_plural = "Рейтинги"


class Reviews(models.Model):
    """Отзывы"""
    email = models.EmailField()
    name = models.CharField("Имя", max_length=100)
    text = models.TextField("Сообщение", max_length=5000)

    parent = models.ForeignKey(
        'self',
        verbose_name="Родитель",
        on_delete=models.SET_NULL,
        blank=True,
        null=True
    )
    movie = models.ForeignKey(
        Movie,
        verbose_name="фильм",
        on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.name} - {self.movie}"

    class Meta:
        verbose_name = "Отзыв"
        verbose_name_plural = "Отзывы"

src/web_site/app04_movies/forms.py
# from django.forms import ModelForm, TextInput
from django import forms

from .models import Reviews, RatingStar, Rating


class ReviewsForm(forms.ModelForm):
    """ Форма отзывов """

    class Meta:
        model = Reviews
        fields = ('name', 'email', 'text')
        widgets = {
            'name': forms.TextInput(attrs={
                'class': 'form-control border'
            }),
            'email': forms.EmailInput(attrs={
                'class': 'form-control border'
            }),
            'text': forms.Textarea(attrs={
                'class': 'form-control border'
            }),
        }


class RatingForm(forms.ModelForm):
    """ Форма добавления рейтинга """
    star = forms.ModelChoiceField(
        queryset=RatingStar.objects.all(),
        widget=forms.RadioSelect(),
        empty_label=None
    )

    class Meta:
        model = Rating
        fields = ("star",)

src/web_site/app04_movies/views.py
from django.db.models import Q
from django.http import HttpResponse, HttpResponseNotFound, Http404
from django.template import RequestContext, loader, Context
from django.views.generic import ListView, DetailView
from django.views.generic.base import View, TemplateView
from django.shortcuts import redirect, render

from .models import Genre, Movie, Actor, Rating
from .forms import ReviewsForm, RatingForm
from .service import get_client_ip


class GenreYear:
    """ Жанры и года выхода фильмов """

    def get_genres(self):
        return Genre.objects.all()

    def get_years(self):
        return Movie.objects.filter(draft=False)


class MoviesView(GenreYear, ListView):
    """ Список фильмов """
    model = Movie
    queryset = Movie.objects.filter(draft=False)
    paginate_by = 6

    # def get_context_data(self, *args, **kwargs):
    #     context = super().get_context_data(*args, **kwargs)
    #     context['categories'] = Category.objects.all()
    #     return context


class MovieDetailView(GenreYear, DetailView):
    """ Полное описание фильма """
    model = Movie
    slug_field = 'url'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['star_form'] = RatingForm()
        context['form'] = ReviewsForm()
        return context


class AddReview(View):
    """ Отзывы """
    def post(self, request, pk):
        qs_obj = Movie.objects.get(id=pk)
        form = ReviewsForm(request.POST)
        if form.is_valid():
            form = form.save(commit=False)
            if request.POST.get('parent', None):
                form.parent_id = int(request.POST.get('parent'))
            form.movie = qs_obj
            form.save()
        return redirect(qs_obj.get_absolute_url())


class ActorView(GenreYear, DetailView):
    """ Вывод информации о актёре """
    model = Actor
    template_name = 'app04_movies/actor.html'
    slug_field = 'name'


class FilterMoviesView(GenreYear, ListView):
    """ Фильтр по годам и жанрам """
    paginate_by = 6

    def get_queryset(self):
        list_years = self.request.GET.getlist('year')
        list_genres = self.request.GET.getlist('genre')

        # queryset = Movie.objects.filter(
        #     Q(year__in=list_years) |
        #     Q(genres__in=list_genres)
        # ).distinct().values('title', 'url', 'poster')

        queryset = Movie.objects.filter(draft=False)
        if "year" in self.request.GET:
            queryset = queryset.filter(year__in=list_years)
        if "genre" in self.request.GET:
            queryset = queryset.filter(genres__in=list_genres)
        queryset = queryset.distinct()
        return queryset

    def get_context_data(self, *args, **kwargs):
        """ Пагинация """
        context = super().get_context_data(*args, **kwargs)
        context['year'] = ''.join(
            [f'year={x}&' for x in self.request.GET.getlist('year')]
        )
        context['genre'] = ''.join(
            [f'genre={x}&' for x in self.request.GET.getlist('genre')]
        )
        return context


class AddStarRating(View):
    """ Добавление рейтинга фильму """

    def post(self, request):
        form = RatingForm(request.POST)
        if form.is_valid():
            Rating.objects.update_or_create(
                ip=get_client_ip(request),
                movie_id=int(request.POST.get('movie')),
                defaults={'star_id': int(request.POST.get('star'))}
            )
            return HttpResponse(status=201)
        else:
            return HttpResponse(status=400)


class Search(ListView):
    """ Поиск фильмов """
    paginate_by = 6

    def get_queryset(self):
        return Movie.objects.filter(
            title__icontains=self.request.GET.get('search').strip()
        )

    def get_context_data(self, *args, **kwargs):
        """ Пагинация """
        context = super().get_context_data(*args, **kwargs)
        context['search'] = f'search={self.request.GET.get("search")}&'
        return context
    #




# def page_not_found_error(request,exception):
#     return render(request, 'pages/404.html',context={'error':'Доступ неверный: не существует'}, status=404)
#
# def page_error(request):
#     return render(request, 'pages/404.html',context={'error':'Доступ неверный: ошибка сервера'}, status=500)

src/web_site/app04_movies/templates/app04_movies/actor.html
{%  extends 'app04_movies/base.html' %}
{% load static %}
            {% block title %} {{ actor.title }} {% endblock title %}  {# Так во вкладке будет название фильма #}

            {% block conteiner %}  {# класс этого блока нужно тут менять от исходного в base потому что sidebar смещается #}
                <div class="container py-md-3">
            {% endblock conteiner %}

            {% block sidebar %}
                <div class="side-bar col-lg-4"> {# Див сайдбара вынесли сюда, чтоб менять его размер тут на 4 #}
            {% endblock sidebar %}

{% block movie %}

<div class="left-ads-display col-lg-7">
    <div class="row">
        <div class="col-md-6">
            <img src="{{ actor.image.url }}" class="img-fluid" alt="">
        </div>
        <div class="desc1-right col-md-6 pl-lg-4">
            <h3 class="editContent">
                {{ movie.title }}
            </h3>
                <h3 class="shop-sing editContent">
                    {{ actor.name }}
                </h3>
            <ul>
                <li>
                    <span>
                        <b>
                            Age:
                        </b>
                        {{ actor.age }}
                    </span>
                </li>
                <li>
                    <span>
                        <b>
                            Film Director:
                        </b>
                        {% for movie in actor.film_director.all %}
                            <a href="{{ movie.get_absolute_url }}">
                                {{ movie.title }}
                            </a>
                            {% if not forloop.last %}
                                <b>, </b>
                            {% endif %}
                        {% endfor %}
{# Для того чтобы отобразить в каких фильмах режисёр или актёр нужно использовать related_name из модели Movie #}
{# Чтобы сослаться на таблицу MtM это film_actor и film_director #}
                    </span>
                </li>
                <li>
                    <span>
                        <b>Actor in films:</b>
                        {% for movie in actor.film_actor.all %}
                            <a href="{{ movie.get_absolute_url }}">
                                {{ movie.title }}
                            </a>
                            {% if not forloop.last %}
                                <b>, </b>
                            {% endif %}
                        {% endfor %}
                    </span>
                </li>
            </ul>
        </div>
    </div>

    <div class="row sub-para-w3layouts mt-5">
        <h3 class="shop-sing editContent">
            About a {{ actor.name }}
        </h3>

        <p class="editContent">

        {# Фильтр safe чтоб теги html от текстового редактора ckeditor рендерились, а не выводились как текст #}
            {{ actor.description|safe }}
        </p>

    </div>
</div>

{% endblock movie %}

src/web_site/app04_movies/templates/app04_movies/base.html
{% extends 'base.html' %}
{% block content %}
{#" Этот кусок общий для двух шаблонов list и detail поэтому он находится здесь #}
        <section class="ab-info-main py-md-5 py-5 editContent" style="padding-left: 3rem; padding-right: 3rem;">

            {% block conteiner %} {# класс этого блока нужно менять на странице deteil, поэтому пихаем в контейнер, потому что sidebar смещается#}
                <div class="container-fluid py-md-3">
            {% endblock conteiner %}

                    <div class="row">
                    {% block offset %}
                    <div class="smd col-lg-1">
                    {% endblock offset %}

                    </div>
                        {% block sidebar %} {# На странице detail меняем класс 2 на 4 так как там меняется размер #}
                            <div class="side-bar col-lg-2"> {# Див сайдбара вынесли сюда, чтоб менять его размер #}
                        {% endblock sidebar %}

                            {% include 'include/sidebar.html' %}
                        </div>
                                {% block movie %}
                                {% endblock movie %}
                    </div>

                </div>
        </section>

{% endblock content %}

src/web_site/app04_movies/templates/app04_movies/movie_detail.html
{%  extends 'app04_movies/base.html' %}
{% load static %}
            {% block title %} {{ movie.title }} {% endblock title %}  {# Название фильма во вкладке #}

            {% block conteiner %}  {# класс этого блока нужно тут менять от исходного в base потому что sidebar смещается #}
                <div class="container py-md-3">
            {% endblock conteiner %}

                    {% block offset %}
                    <div class="smd col-lg-0">
                    {% endblock offset %}


            {% block sidebar %}
                <div class="side-bar col-lg-4"> {# Див сайдбара вынесли сюда, чтоб менять его размер тут на 4 #}
            {% endblock sidebar %}

{% block movie %}

<div class="left-ads-display col-lg-8">
    <div class="row">
        <div class="col-md-6">
            <img src="{{ movie.poster.url }}" class="img-fluid" alt="">
        </div>
        <div class="desc1-right col-md-6 pl-lg-4">

        <h3 class="shop-sing editContent" style="outline: none; cursor: inherit;">
            {{ movie.title }}
        </h3>

            <h5 class="editContent"></h5>
            <ul>
                <li>
                    <span>
                        <b>Year:</b> {{ movie.year }}
                    </span>
                </li>
                <li>
                    <span>
                        <b>Country:</b> {{ movie.country }}
                    </span>
                </li>
                <li>
                    <span>
                        <b>Directors:</b>
                    {% for director in movie.directors.all %}
                        <a href="{{ director.get_absolute_url }}">
                            {{ director.name }}
                        </a>
                        {% if not forloop.last %}
                            <b>, </b>
                        {% endif %}
                    {% endfor %}
                    </span>
                </li>
                <li>
                    <span>
                        <b>Actors:</b>
                    {% for actor in movie.actors.all %}
                        <a href="{{ actor.get_absolute_url }}">
                        {{ actor.name }}
                        </a>
                        {% if not forloop.last %}
                            <b>, </b>
                        {% endif %}
                    {% endfor %}
                    </span>
                </li>
                <li>
                    <span>
                        <b>Genre:</b>
                    {% for genre in movie.genres.all %}
                        {{ genre.name }}
                        {% if not forloop.last %}
                            <b>, </b>
                        {% endif %}
                    {% endfor %}
                </span>
                </li>
                <li style="list-style: none">
                    <span><b>Premiere:</b> {{ movie.world_premiere }}</span>
                </li>
                <li style="list-style: none">
                    <span><b>Seasons:</b> {{ movie.seasons }}</span></li>
                <li style="list-style: none">
                    <span><b>Series:</b> {{ movie.series }}</span>
                </li>


                <li>
                    <form action="{% url 'add-rating' %}" method="post" name="rating">
                        {% csrf_token %}
                        <b>Rating:</b>

                        {# Скрытое поле с id фильма #}
                        <input type="hidden" value="{{ movie.id }}" name="movie">

                            <span class="rating">
                                {% for k, v in star_form.fields.star.choices %} {# получам список звёзд в виде кортежа #}
                                    <input id="rating {{ v }}" type="radio" name="star" value="{{ k }}">
                                    <label for="rating {{ v }}>{{ k }}">
                                    </label>
                                {% endfor %}
                           </span>
{#                        <span class="editContent">4.0</span>#}
                    </form>

                </li>


                <div class="share-desc">
                    <div class="share">
                        <h4 class="editContent"
                            style="outline: none; cursor: inherit;">
                            Share:</h4>
                        <ul class="w3layouts_social_list list-unstyled">
                            <li>
                                <a href="#" class="w3pvt_facebook editContent"
                                   style="outline: none; cursor: inherit;">
                                <span class="fa fa-facebook-f"
                                      style="outline: none; cursor: inherit;"></span>
                                </a>
                            </li>
                            <li>
                                <a href="#" class="w3pvt_twitter editContent"
                                   style="outline: none; cursor: inherit;">
                                <span class="fa fa-twitter"
                                      style="outline: none; cursor: inherit;"></span>
                                </a>
                            </li>
                            <li>
                                <a href="#" class="w3pvt_dribble editContent"
                                   style="outline: none; cursor: inherit;">
                                <span class="fa fa-dribbble"
                                      style="outline: none; cursor: inherit;"></span>
                                </a>
                            </li>
                        </ul>
                    </div>
                    <div class="clearfix"></div>
                </div>
            </ul>
        </div>
    </div>
    <div class="row sub-para-w3layouts mt-5">

        <h3 class="shop-sing editContent" style="outline: none; cursor: inherit;">
            About the movie "{{ movie.title }}"</h3>
        <p>
            {% for obj in movie.movieshots_set.all %}
            <img  src="{{ obj.image.url }}" style=" max-height: 140px; height: auto;" {# class=".img-movie-shots" #} alt="" {{ obj.description }}>
            {% endfor %}
        </p>

        <p class="editContent" style="outline: none; cursor: inherit;">
            {{ movie.description|safe }}
        </p>
        <p class="mt-3 italic-blue editContent"
           style="outline: none; cursor: inherit;">
            <iframe width="560" height="315"
                    src="{{ movie.trailer_url }}"
                    frameborder="0" allow="accelerometer; autoplay;
                                                           encrypted-media; gyroscope; picture-in-picture"
                    allowfullscreen>

            </iframe>


        </p>
    </div>
    <hr>
    <div class="row">
        <div class="single-form-left">
            <!-- contact form grid -->
            <div class="contact-single">
                <h3 class="editContent">
{#                    <span class="sub-tittle editContent">{{ movie.reviews_set.count }}</span>Leave a review</h3>#}
                    <span class="sub-tittle editContent"></span>Leave a review</h3>


                <form action="{% url 'add-review' movie.id %}" method="post" class="mt-4" id="formReview"> {% csrf_token %}

                    <input type="hidden" name="parent" id="contactparent" value="">

                    <div class="form-group editContent">

                        <label for="contactcomment" class="editContent">
                            Your comment *
                        </label>
                            {{ form.text }}
{#                        <textarea class="form-control border" rows="5" name="text"#}
{#                                  id="contactcomment" required=""></textarea>#}
                    </div>
                    <div class="d-sm-flex">
                        <div class="col-sm-6 form-group p-0 editContent">

                            <label for="contactusername" class="editContent">
                                Name *
                            </label>
                            {{ form.name }}
{#                            <input type="text" class="form-control border"#}
{#                                   id="contactusername" required="" name="name">#}
                        </div>
                        <div class="col-sm-6 form-group ml-sm-3 editContent">

                            <label for="contactemail" class="editContent">
                                Email *
                            </label>
                            {{ form.email }}
{#                            <input type="email" class="form-control border"#}
{#                                   id="contactemail" required="" name="email">#}
                        </div>
                        </div>
                        <button type="submit" class="mt-3 btn btn-success btn-block py-3">
                            Send
                        </button>
                </form>

            </div>
        </div>
            <!--  //contact form grid ends here -->
    </div>


{#----------------------------------------#}
{#{% for review in movie.reviews_set.all %}#}
{# Тут мы выводим сразу все коменты и родители от ответы, визуально всё одинаково #}


    {% for review in movie.get_review %}
{# В этом варианте фунция get_review в модели фильтрует только коменты к #}
{# фильму, без ответов на них и мы выводим сначала только их #}
    <div class="media py-5">
        <img src="{% static 'images/te2.jpg' %}" class="mr-3 img-fluid" alt="image">
        <div class="media-body mt-4">

            <h5 class="mt-0 editContent">
                {{ review.name }}
            </h5>
            <p class="mt-2 editContent">
                {{ review.text }}
            </p>

            {# Ссылка для ответа на коммент, formReview это наше id формы #}
{# Функция addReview() написанная ниже в скрипте, вызовется по клику, будет передавать имя и id пользователя которому хотим ответить #}
            <a href="#formReview" onclick="addReview( '{{ review.name }}', '{{ review.id }}' )">Reply</a>

{#----------------------------------------#}

            {% for rew in review.reviews_set.all %}
                <div class="media mt-5 editContent"
                     style="outline: none; cursor: inherit;">
                    <a class="pr-3" href="#">
                        <img src="{% static 'images/te1.jpg' %}" class="img-fluid " alt="image">
                    </a>
                    <div class="media-body">
                        <h5 class="mt-0 editContent">
                            {{ rew.name }}
                        </h5>
                        <p class="mt-2 editContent">
                            {{ rew.text }}
                        </p>
                    </div>
                </div>
            {% endfor %}

{#----------------------------------------#}
        </div>
    </div>
    {% endfor %}

</div>
</div>
</div>


    <script>
    function addReview(name, id) {
        document.getElementById('contactparent').value = id;
        document.getElementById('contactcomment').innerText = name + ', '
    }
    </script>

{% endblock movie %}

src/web_site/app04_movies/templates/app04_movies/movie_list.html
{% extends 'app04_movies/base.html' %}
{% load static %}

{% block header %}
    <img src="{% static 'single-post-pic.jpg' %}"  style="width: 100%;" />
{% endblock header %}


{% block movie %}

    <div class="left-ads-display col-lg-8">
        <div class="row">

            {% for movie in movie_list %}
            <div class="col-md-4 product-men">
                <div class="product-shoe-info editContent text-center mt-lg-4" >
                    <div class="men-thumb-item">
                        <img src="{{ movie.poster.url }}" class="img-fluid" alt="" width="450" height="250" >
                    </div>
                    <div class="item-info-product">
                        <h4 class="">
                            <a href="{{ movie.get_absolute_url }}" class="editContent" >
                                {{ movie.title }}
                            </a>
                        </h4>

                        <div class="product_price">
                        </div>

                        <ul class="stars">
                            <li><a href="#"><span class="fa fa-star" aria-hidden="true" ></span></a></li>
                            <li><a href="#"><span class="fa fa-star" aria-hidden="true" ></span></a></li>
                            <li><a href="#"><span class="fa fa-star-half-o" aria-hidden="true" ></span></a></li>
                            <li><a href="#"><span class="fa fa-star-half-o" aria-hidden="true" ></span></a></li>
                            <li><a href="#"><span class="fa fa-star-o" aria-hidden="true" ></span></a></li>
                        </ul>
                    </div>
                </div>
            </div>

            {% endfor %}
        </div>

        <div class="grid-img-right mt-4 text-right bg" >
            {% include 'include/pagination.html'%}
        </div>

    </div>

{% endblock movie %}